spring.application.name=module2
spring.h2.console.enabled=true

spring.datasource.url=jdbc:h2:file:/Users/ankush/Documents/sprintboot/db
spring.datasource.username=ankkushh
spring.datasource.password=Ankush511
spring.jpa.hibernate.ddl-auto=create